# Generated by Django 4.2.6 on 2024-05-29 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comercio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='marca',
            table='Almacen_marca',
        ),
        migrations.AlterModelTable(
            name='pedido',
            table='Almacen_pedido',
        ),
        migrations.AlterModelTable(
            name='producto',
            table='Almacen_producto',
        ),
        migrations.AlterModelTable(
            name='productopedido',
            table='Almacen_productopedido',
        ),
    ]
